using AutoIssueResolver.Persistence.EntityConfiguration;

namespace AutoIssueResolver.Persistence.Sqlite.EntityConfiguration;

public class EfApplicationRunConfigurationSqlite: EfApplicationRunConfiguration
{ }