// <auto-generated />
using System;
using AutoIssueResolver.Persistence.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoIssueResolver.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(ReportingContextSqlite))]
    [Migration("20250618091549_V1.0.1")]
    partial class V101
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("AutoIssueResolver.Persistence.Abstractions.Entities.EfApplicationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRuns");
                });

            modelBuilder.Entity("AutoIssueResolver.Persistence.Abstractions.Entities.EfRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSmellReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRunId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AutoIssueResolver.Persistence.Abstractions.Entities.EfRequest", b =>
                {
                    b.HasOne("AutoIssueResolver.Persistence.Abstractions.Entities.EfApplicationRun", "ApplicationRun")
                        .WithMany("Requests")
                        .HasForeignKey("ApplicationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRun");
                });

            modelBuilder.Entity("AutoIssueResolver.Persistence.Abstractions.Entities.EfApplicationRun", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
